# .github/workflows/build-portable-windows.yml
name: Build Portable Windows Console App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        runtime: [ win-x64, win-arm64 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish portable self-contained EXE
        run: |
          dotnet publish \
            --configuration Release \
            --runtime ${{ matrix.runtime }} \
            --self-contained true \
            -p:PublishSingleFile=true \
            -p:PublishTrimmed=true \
            -p:IncludeNativeLibrariesForSelfExtract=true \
            -p:UseAppHost=true \
            -o ${{ github.workspace }}/publish/${{ matrix.runtime }}

      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: portable-${{ matrix.runtime }}
          path: publish/${{ matrix.runtime }}/
