# .github/workflows/build-and-release.yml
name: Build and Release Portable Windows Console App

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Publish self-contained EXE for Windows
        run: dotnet publish --configuration Release --runtime win-x64 --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true -p:IncludeNativeLibrariesForSelfExtract=true -p:UseAppHost=true -o publish

      - name: Rename EXE for clarity
        run: Rename-Item -Path "publish\YourAppName.exe" -NewName "YourAppName-win-x64.exe"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: publish/WakeupXI.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
